### PR TITLE
Create a sample app using Express, PostgreSQL and Prisma

### PR DESCRIPTION
**Pull request by starvader13**
This PR aims to Solve https://github.com/keploy/keploy/issues/2136

**Features Added:**
- [X] ORM: `Prisma`
- [X] Database: `PostgreSQL`
- [X] `Database Schema`
- [X] Route: `add`
- [X] Route: `update`
- [X] Route: `delete`
- [X] Route: `view`
- [X] Route: `view/:id`
- [X] Route: `change-priority/:id`
- [X] Docs: `Swagger`
image
- [X] README.md
- [X] Testing: `Keploy`
image
- [X] KEPLOY.md

### CODE REVIEW

**Comment by starvader13** [comment]
@Sonichigo @Swpn0neel If this meets the project's requirements, I will proceed with Keploy testing and update the README documentation accordingly.

**Comment by Sonichigo** [comment]
@starvader13 looks good you can mark it ready for review!

**Comment by starvader13** [comment]
@Sonichigo Do I need to push the keploy/reports and keploy-generated test files too?

**Comment by Sonichigo** [comment]
> @Sonichigo Do I need to push the keploy/reports and keploy-generated test files too?
> 
> Also, do you want me to add a docker file for setting up this project?

You can Dockerfile to this project. rest isn't required

**Review by Sonichigo — APPROVED** [review]
LGTM @starvader13 !!! Just merge keploy.md and readme.md. 
Also in `.env` it would be good to add port is for application.

During npm run migrate, i got error Direct_URL is empty since it was in comments and i'm not using supabase. It would be great to add this in comments in `schema.prisma` and `.env`

**Comment by starvader13** [comment]
> LGTM @starvader13 !!! Just merge keploy.md and readme.md. Also in `.env` it would be good to add port is for application.
> 
> During npm run migrate, i got error Direct_URL is empty since it was in comments and i'm not using supabase. It would be great to add this in comments in `schema.prisma` and `.env`

@Sonichigo I have made all these changes. 

> You can Dockerfile to this project. rest isn't required

I am working on adding a Dockerfile to this project, which might take some time. If possible, we can reference this task in a new issue. I can then work on that issue, and we can merge this PR as it's completed.

**Review by Sonichigo — APPROVED** [review]

**Pull request merged**
